name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      presto:
        image: ahanaio/prestodb-sandbox
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
